### ISSUE TITLE
Tables & Figures

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#13]
Add support for Figures and Tables in the syllabus content.

Acceptance criteria:
1. Figures are stored as image files in a specific folder
2. Figures are referenced as image files in the markdown
3. Figures can have text describing their content below the table
4. Figures are numbered
5. List of figures can be generated at the end of the document
6. Tables are defined in standard MD format
7. Tables can have text describing their content
8. Tables are numbered
9. List of tables can be generated at the end of the document

**Comment by Witiko** [comment]
@danopolan Before starting the implementation, I have a number of clarifying questions.

> 1. Figures are stored as image files in a specific folder

Figures are stored in folder `img/`, as described in https://github.com/danopolan/istqb_latex/issues/18#issuecomment-1582454977.

> 2. Figures are referenced as image files in the markdown
> 3. Figures can have text describing their content below the table

Images including captions can be input using standard Markdown syntax:

``` md
![label](image.jpg "Here is a caption describing the image")
```

In LaTeX, figures are typically not inserted immediately, but they may float to the next page. Do we want this?

If we want images floating, there should be a way to reference them from the text. I can make it so that authors can write:

``` md
See <figure:label>.
```

Here, `<image:label>` would be replaced by the text `Figure XY`. Is this desirable?

Furthermore, authors may want to influence the image size. I can make it so that authors can write:

    ![label](image.jpg){width=2cm}

Is this desirable?

> 4. Figures are numbered.

The caption would be prefixed with Figure X, where X is 1, 2, 3, ... Is this the desired format?

> 5. List of figures can be generated at the end of the document.

Is there an example of the list of figures, which would show the specific formatting we should follow, or is this flexible?

> 6. Tables are defined in standard MD format

Markdown does not support tables out-of-box. We support the pipeTables syntax extension, which allows authors to type simple tables including captions, such as:

``` md
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |

: Here is a caption describing the table. `\label{table:label}`{=tex}
```

However, pipeTables do not enable complex tables with merged and/or colored cells, such as the ones shown in [ISTQB_CTFL_Syllabus-v4.0.pdf](https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CTFL_Syllabus-v4.0.pdf), page 64. Is support for such rich tables desirable?

For rich tables, the authors would have to drop down to LaTeX:

`````` md
``` {=tex}
\begin{table}
\begin{tabular}
% ...
\end{tabular}
\caption{Here is a caption describing the table.}
\label{table:label}
\end{table}
```
``````

As with figures, tables are typically not inserted immediately, but they may float to the next page. Do we want this?

If we want tables floating, there should be a way to reference them from the text. I can make it so that authors can write:

``` md
See <table:label>.
```

Here, `<table:label>` would be replaced by the text `Table XY`. Is this desirable?

> 8. Tables are numbered.

As with figures, the caption would be prefixed with Table X, where X is 1, 2, 3, ... Is this the desired format?

> 9. List of tables can be generated at the end of the document

As with figures, is there an example of the list of tables, which would show the specific formatting we should follow, or is this flexible?

**Comment by danopolan** [comment]
@Witiko basically answers to all your questions are Yes.
1. Images can be stored in `img/` folder
2. Referencing images is fine in standard MD syntax
3. Image captions using `<figure:label>` and `![label](image.jpg "Here is a caption describing the image"){width=2cm}` would be great. But I would not have it floating. It should be placed where author wants it.
4. Numbering figures as you proposed
5. If there is no format defined in Word template there is nothing specific for list of figures. Use standard heading and list as for e.g. bibliography
6. pipeTables is anought. Other tables can be added as images
7. Floating tables is not desired here. Keep it where author defines it.
8. Numbering tables as you proposed
9. Same as #5

**Comment by Witiko** [comment]
Ad 6: At the moment, support for attributes on tables is a work-in-progress, see also https://github.com/Witiko/markdown/issues/310. For the moment, I will use the following syntax:

``` tex
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |

: Here is a caption describing the table. `\label{table:label}`{=tex}
```

When the support is ready, we can switch to a more recent version of the Markdown package and use the more pleasant syntax outlined in https://github.com/danopolan/istqb_latex/issues/13#issuecomment-1603430424. Doesn't seem like a blocker for the initial version of the template, though.
