### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#18]
Define a repository structure that will be clean and understandable for every syllabus author.

**Comment by Witiko** [comment]
Here is the current repository structure as I understand it (corrections welcome):

1. `main.tex` -- An example ISTQB syllabus that includes the markdown documents `example-intro.md` and `example-istqb-content.md`.
2. `latex.tex` -- An example LaTeX document that includes the markdown document `example.md`.
7. `markdown.lua`, `markdown.sty`, `markdown.tex` -- The Markdown package for TeX v2.8.1 from 2019-04-30.
8. `refs.bib` -- Bibliographic database in [the BibLaTeX format (Section 2)][6].
3. `content/` -- Contains markdown documents (`0-intoduction.md`, `1-intro.md`, ...) to be used in the future.
4. `img/` -- Contains images (`istqb-logo.png`) used in `main.tex` and other LaTeX documents in the future.
5. `release/` -- Contains PDF document (`ISTQB_CTFL_2018.pdf`) produced by typesetting `main.tex`.
6. `.github/workflows/` -- Contains configuration files for GitHub's continuous integration (CI).

Here are my suggestions with respect to the directory structure:

1. Use at least one leading zero for files `content/*.md` for predictable ordering with 10 and more markdown documents.
2. Remove `release/`, save typeset documents in CI either as artifacts or [within automatically produced prereleases][2].
3. Remove `markdown.lua`, `markdown.sty`, and `markdown.tex` and use either [the `witiko/markdown` Docker image][5] or [the `texlive/texlive` Docker image][7]. This requires updating the Markdown package for TeX to at least to v2.11.0 from 2021-10-01.
4. Remove `latex.tex` and `example.md`, which seem to have been superseded by `main.tex` and `example-*.md`.

Here are other assorted suggestions that are not yet covered by the open issues:

5. If we don't want to remove `latex.tex`, then in `latex.tex`, [the markdown code is not indented][3] to prevent interpretation as a code block. [The `stripIndent` option][4] can be used to inform the Markdown package about the current indent, so that this is unnecessary. This requires updating the Markdown package for TeX to at least to v2.10.0 from 2021-08-07.
6. In `main.tex`, [images from `img/` are included using explicit path and suffix][1]. Neither is necessary in LaTeX:
    ``` latex
    \graphicspath{{./img}{.}}  % Look for images first in ./img and then in ./
    \chead{\includegraphics[width=2cm]{istqb-logo}}  % Look for different images with known suffixes
    ```
    This has a number of benefits:
    1. less typing for the authors (`./img/istqb-logo.png` -> `istqb-logo`) and
    2. more flexibility for us (rename `img/` or change PNG to PDF without touching LaTeX or markdown documents).
7. Do not use the `hybrid` option in `main.tex`. Better options for mixing markdown with LaTeX include:
    1. [option `contentBlocks`][9], available since Markdown v2.4.0 from 2017-03-27,
    2. [option `rawAttribute`][8], available since Markdown v2.18.0 from 2022-10-30, and
    3. [options `texMathDollars`][10], [`texMathSingleBackslash`][11], and [`texMathDoubleBackslash`][12] available since Markdown v2.22.0 from 2023-04-02.

 [1]: https://github.com/danopolan/istqb_latex/blob/74687258674f36d0c3657639d573f069038e5db7/main.tex#L35
 [2]: https://github.com/marketplace/actions/automatic-releases
 [3]: https://github.com/danopolan/istqb_latex/blob/74687258674f36d0c3657639d573f069038e5db7/latex.tex#L23-L25
 [4]: https://witiko.github.io/markdown/#option-stripindent
 [5]: https://hub.docker.com/r/witiko/markdown/tags
 [6]: http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf
 [7]: https://hub.docker.com/r/texlive/texlive
 [8]: https://witiko.github.io/markdown/#option-rawattribute
 [9]: https://witiko.github.io/markdown/#option-contentblocks
 [10]: https://witiko.github.io/markdown/#option-texmathdollars
 [11]: https://witiko.github.io/markdown/#option-texmathsinglebackslash
 [12]: https://witiko.github.io/markdown/#option-texmathdoublebackslash
