### ISSUE TITLE
ATLaS syllabus chapters are not identified properly

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#34]
Chapter for ATLaS syllabus are not identified correctly and the resulting PDF is a chaos.
We want:

1. Chapter numbering starting with 0
2. Chapters are ordered based on input files (00-intoduction.md, 01-intro.md, 01-quality-assistance.md, 02-intro.md, etc.)
3. Each chapter starts with the intro page listing keywords and learning objectives 
4. Table of content is generated for the whole syllabus
5. Bibliography is generated based on bibliography.bib

See https://github.com/danopolan/istqb_latex/actions/runs/5579906227

**Comment by Witiko** [comment]
> 1. Chapter numbering starting with 0

It does start from 0, see example.pdf. There is an encoding issue with the text files in md/, which start with the U+FEFF (byte order mark) character.

![image](https://github.com/danopolan/istqb_latex/assets/603082/2797e686-0833-40e2-b2e8-68fe1e6d0d87)

This prevents the first heading in the file from being read correctly, because the line does not start with a hash sign (`#`), but with the byte order mark:

![image](https://github.com/danopolan/istqb_latex/assets/603082/fc27d03a-8251-4d98-a4fe-ebc655d4b1a3)

I can add a preprocessing to the CI to ensure that the files in md/ are encoded in UTF-8 without byte order mark using the following command:

```
dos2unix md/*
```

> 2. Chapters are ordered based on input files (00-intoduction.md, 01-intro.md, 01-quality-assistance.md, 02-intro.md, etc.)

They are ordered based on the contents of atlas.tex. Namely, new files added to md/ won't just appear in the output, they need to be listed in atlas.tex. Which they are at the moment. I am just making sure that this point is clear, because #35 was due to files being deleted in md/ but not in atlas.tex.

> 3. Each chapter starts with the intro page listing keywords and learning objectives.

> 4. Table of content is generated for the whole syllabus

In example.tex, the [hashEnumerators](https://witiko.github.io/markdown/#option-hashenumerators) syntax extension is enabled, which allows authors to write ordered lists as follows:

```
#. First item
#. Second item
#. Third item
```

However, in atlas.tex, hashEnumerators (and a number of other syntax extensions) were not enabled. When hashEnumerators is not enabled, the above code would be interpreted as chapter headings, which explains the "chaos" in atlas.pdf you described:

![image](https://github.com/danopolan/istqb_latex/assets/603082/fa18e03e-affe-470f-91f4-5e5ed04900f1)
![image](https://github.com/danopolan/istqb_latex/assets/603082/796b88d8-cc1a-4d6b-b9c0-558c889c3c75)

I can enable hashEnumerators in atlas.tex as well.

> 5. Bibliography is generated based on bibliography.bib

Only cited references appear in the bibliography. Is this undesirable?

**Comment by danopolan** [comment]
> I can add a preprocessing step to the CI to ensure that the files in md/ are encoded in UTF-8 without byte order mark.

Please do. Thx. I have fixed encodings already to UTF-8

> They are ordered based on the contents of atlas.tex. Namely, new files added to md/ won't just appear in the output, they need to be listed in atlas.tex.

Already committed. 

> I can enable hashEnumerators in atlas.tex as well.

Please do.

> Only cited references appear in the bibliography.

We want all references to appear in the PDF, regardless if there are cited or not.

**Comment by danopolan** [comment]
Ok, it's great knowing that, there is a possibility of doing it, despite the limitation of the misc entry type.
Let's do the implementation by keeping sections as they are now, despite of citing them or not.
I will get more details on this in the evening.
