### ISSUE TITLE
Tables with images

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#66]
Add support for images within tables, which is currently not supported in Markdown. The build is failing due to that (https://github.com/danopolan/istqb_latex/actions/runs/5632205963).

There is a possible workaround for simple tables of two columns to have them as separate images with caption. But there could be cases where table with image will get more complicated.

Example of such a table is in [ATLaS BoK](https://github.com/danopolan/istqb_latex/blob/2a4634a46929f2361b0d6187acdaa56a06963f27/bok-md/02-improve-quality.md?plain=1#L48)

**Comment by Witiko** [comment]
Here is a workaround that involves writing LaTeX code:

``` diff
  | Notation | Meaning |
  | -------- | ------- |
< | ![workingStep](fig/working-step.eps){width=2cm} | A working step or process activity. |
> | `\includegraphics[width=2cm]{fig/working-step.eps}`{=tex} | A working step or process activity. |
```

Alternatively, merging #69 allows you use images in tables without writing LaTeX.

**Comment by Witiko** [comment]
As an aside, I noticed that a directory fig/ was created in the repo and contains figures for ATLaS. Moving the figures from fig/ to img/ would remove needless redundancy (it's not clear why they should be separate) and will also allow you to omit the prefix fig/ from the images:

``` md
| ![workingStep](working-step.eps){width=2cm} | A working step or process activity. |
```

This is because the directory img/ is special-cased and LaTeX will also search for images there:

https://github.com/danopolan/istqb_latex/blob/914cb16407fd403ca6f85344f1a435131366fc19/istqb.cls#L166-L168

Furthermore, you can also omit the suffix. LaTeX will always look for all known image suffixes:

``` md
| ![workingStep](working-step){width=2cm} | A working step or process activity. |
```

Hopefully, this will save you some typing and help the writers avoid typos.

**Comment by danopolan** [comment]
The `fig/` folder was created by my colleague and can be merged into `img/` folder for sure. I would just need to update all references to images in BOK files. So I will keep that as a separate issue #72
